### PR TITLE
Refactor

### PR DESCRIPTION
**Pull request by nickode**
Pushing the final code of Sprint 3 into the Master branch. Review is needed by the assignees.

### CODE REVIEW

**Comment by MNezameddin** [comment]
Currently Reviewing this request. Will let you know if there is anything that breaks.

**Comment by rThamb** [comment]
Revise comments for map.component and indoorService. Some clean up is also required for some classes.

**Comment by nickode** [comment]
Added more comments to the MapComponent class where I noticed were missing. Please review.

**Comment by MNezameddin** [comment]
Directions component is good for the most part, but missing comments and cleanliness for the most recent changes. Please refactor this.

**Comment by MNezameddin** [comment]
Code works as predicted and has no fatal errors. No issues other than previously documented bugs, which will be resolved in later sprints. So far code works fine and is stable to be pushed since it's been tested and worked on previously in the refactor branch.

I approve of the following commits and changes.

**Pull request merged**
